# Generated by Django 4.2.28 on 2026-02-09 09:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import questions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='削除済み')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('body', models.TextField(verbose_name='回答本文')),
                ('body_format', models.CharField(choices=[('html', 'HTML'), ('markdown', 'Markdown'), ('text', 'テキスト')], default='text', max_length=10, verbose_name='本文フォーマット')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='AI生成')),
                ('ai_model', models.CharField(blank=True, max_length=50, verbose_name='AIモデル')),
                ('ai_generation_status', models.CharField(choices=[('none', '対象外'), ('pending', '生成中'), ('completed', '完了'), ('failed', '失敗')], default='none', max_length=10, verbose_name='AI生成ステータス')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='削除実行者')),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='削除済み')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('title', models.CharField(max_length=200, verbose_name='質問タイトル')),
                ('custom_subject', models.CharField(blank=True, help_text='「その他」選択時に入力', max_length=50, verbose_name='カスタム教科名')),
                ('body', models.TextField(verbose_name='本文')),
                ('body_format', models.CharField(choices=[('html', 'HTML'), ('markdown', 'Markdown'), ('text', 'テキスト')], default='text', max_length=10, verbose_name='本文フォーマット')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='解決済み')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='削除実行者')),
            ],
            options={
                'verbose_name': '質問',
                'verbose_name_plural': '質問',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='教科名')),
                ('is_custom', models.BooleanField(default=False, verbose_name='カスタム教科')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除済み')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'verbose_name': '教科',
                'verbose_name_plural': '教科',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='削除済み')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('file', models.FileField(upload_to=questions.models.question_media_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'mp3', 'wav', 'ogg', 'm4a', 'mp4', 'webm', 'mov', 'avi', 'pdf', 'doc', 'docx', 'txt'])], verbose_name='ファイル')),
                ('media_type', models.CharField(choices=[('image', '画像'), ('audio', '音声'), ('video', '動画'), ('other', 'その他')], default='other', max_length=10, verbose_name='メディア種別')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='ファイルサイズ（バイト）')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='元ファイル名')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='削除実行者')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='questions.question', verbose_name='質問')),
            ],
            options={
                'verbose_name': '質問メディア',
                'verbose_name_plural': '質問メディア',
            },
        ),
        migrations.CreateModel(
            name='QuestionDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='タイトル')),
                ('subject_id', models.IntegerField(blank=True, null=True, verbose_name='教科ID')),
                ('custom_subject', models.CharField(blank=True, max_length=50, verbose_name='カスタム教科')),
                ('body', models.TextField(blank=True, verbose_name='本文')),
                ('body_format', models.CharField(blank=True, max_length=10, verbose_name='フォーマット')),
                ('auto_saved_at', models.DateTimeField(auto_now=True, verbose_name='自動保存日時')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='questions.question', verbose_name='対象質問')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_drafts', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name': '質問下書き',
                'verbose_name_plural': '質問下書き',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questions.subject', verbose_name='教科'),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='質問者'),
        ),
        migrations.CreateModel(
            name='AnswerMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='削除済み')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('file', models.FileField(upload_to=questions.models.answer_media_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'mp3', 'wav', 'ogg', 'm4a', 'mp4', 'webm', 'mov', 'avi', 'pdf', 'doc', 'docx', 'txt'])], verbose_name='ファイル')),
                ('media_type', models.CharField(choices=[('image', '画像'), ('audio', '音声'), ('video', '動画'), ('other', 'その他')], default='other', max_length=10, verbose_name='メディア種別')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='ファイルサイズ（バイト）')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='元ファイル名')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='questions.answer', verbose_name='回答')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='削除実行者')),
            ],
            options={
                'verbose_name': '回答メディア',
                'verbose_name_plural': '回答メディア',
            },
        ),
        migrations.CreateModel(
            name='AnswerDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, verbose_name='本文')),
                ('body_format', models.CharField(blank=True, max_length=10, verbose_name='フォーマット')),
                ('auto_saved_at', models.DateTimeField(auto_now=True, verbose_name='自動保存日時')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='questions.answer', verbose_name='対象回答')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_drafts', to='questions.question', verbose_name='対象質問')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_drafts', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name': '回答下書き',
                'verbose_name_plural': '回答下書き',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question', verbose_name='質問'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='回答者'),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji_type', models.CharField(choices=[('thumbs_up', '👍'), ('thumbs_down', '👎'), ('heart', '❤️'), ('celebration', '🎉'), ('idea', '💡')], max_length=20, verbose_name='絵文字種別')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='questions.answer', verbose_name='回答')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name': 'リアクション',
                'verbose_name_plural': 'リアクション',
                'unique_together': {('answer', 'user', 'emoji_type')},
            },
        ),
    ]
