# Generated by Django 4.2.28 on 2026-02-13 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='groups.studygroup', verbose_name='共有グループ'),
        ),
        migrations.AddField(
            model_name='question',
            name='visibility',
            field=models.CharField(choices=[('public', '全体公開'), ('group', 'グループ内')], default='public', max_length=10, verbose_name='公開範囲'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='削除済み')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('body', models.TextField(verbose_name='返信本文')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='AI生成')),
                ('ai_model', models.CharField(blank=True, max_length=50, verbose_name='AIモデル')),
                ('ai_generation_status', models.CharField(choices=[('none', '対象外'), ('pending', '生成中'), ('completed', '完了'), ('failed', '失敗')], default='none', max_length=10, verbose_name='AI生成ステータス')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='questions.answer', verbose_name='回答')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='削除実行者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', to=settings.AUTH_USER_MODEL, verbose_name='返信者')),
            ],
            options={
                'verbose_name': '返信',
                'verbose_name_plural': '返信',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('annotation_type', models.CharField(choices=[('formula', '数式導出'), ('word', '単語説明'), ('supplement', '補完情報')], max_length=20, verbose_name='注釈種別')),
                ('selected_text', models.TextField(verbose_name='選択テキスト')),
                ('context_before', models.TextField(blank=True, verbose_name='前文脈')),
                ('context_after', models.TextField(blank=True, verbose_name='後文脈')),
                ('explanation', models.TextField(verbose_name='AI説明（Markdown）')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='questions.answer', verbose_name='回答')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'AI注釈',
                'verbose_name_plural': 'AI注釈',
            },
        ),
    ]
