# Generated by Django 4.2.28 on 2026-02-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_group_question_visibility_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_style',
            field=models.CharField(choices=[('normal', '通常'), ('slide', 'スライド')], default='normal', max_length=10, verbose_name='回答スタイル'),
        ),
    ]
