# Generated by Django 4.2.28 on 2026-02-14 08:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0004_ai_usage_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='emoji_type',
            field=models.CharField(choices=[('thumbs_up', '👍'), ('thumbs_down', '👎')], max_length=20, verbose_name='絵文字種別'),
        ),
        migrations.CreateModel(
            name='ReplyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='削除済み')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('file', models.FileField(upload_to=questions.models.reply_media_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'mp3', 'wav', 'ogg', 'm4a', 'mp4', 'webm', 'mov', 'avi', 'pdf', 'doc', 'docx', 'txt'])], verbose_name='ファイル')),
                ('media_type', models.CharField(choices=[('image', '画像'), ('audio', '音声'), ('video', '動画'), ('other', 'その他')], default='other', max_length=10, verbose_name='メディア種別')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='ファイルサイズ（バイト）')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='元ファイル名')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='削除実行者')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='questions.reply', verbose_name='返信')),
            ],
            options={
                'verbose_name': '返信メディア',
                'verbose_name_plural': '返信メディア',
            },
        ),
    ]
