# Generated by Django 4.2.28 on 2026-02-09 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='対象ID')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='削除日時')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='対象モデル')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='削除実行者')),
            ],
            options={
                'verbose_name': '削除ログ',
                'verbose_name_plural': '削除ログ',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
