# Generated by Django 4.2.28 on 2026-02-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='original_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='削除前メールアドレス'),
        ),
        migrations.AddField(
            model_name='user',
            name='original_username',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='削除前ユーザ名'),
        ),
    ]
