# Generated by Django 4.2.28 on 2026-02-14 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_original_email_user_original_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='自己紹介'),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, help_text='例: 高校2年、学部3年、主任', max_length=50, verbose_name='学年・役職'),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, help_text='例: 高校生、大学生、会社員、教師', max_length=100, verbose_name='職業・身分'),
        ),
        migrations.AddField(
            model_name='user',
            name='workplace_school',
            field=models.CharField(blank=True, help_text='例: ○○高校、△△大学', max_length=200, verbose_name='所属（学校・職場）'),
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'スパム・迷惑行為'), ('inappropriate', '不適切なコンテンツ'), ('harassment', '嫌がらせ'), ('impersonation', 'なりすまし'), ('other', 'その他')], max_length=20, verbose_name='通報理由')),
                ('detail', models.TextField(blank=True, max_length=500, verbose_name='詳細')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='通報日時')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='対応済み')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='被通報ユーザ')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='通報者')),
            ],
            options={
                'verbose_name': 'ユーザ通報',
                'verbose_name_plural': 'ユーザ通報',
                'ordering': ['-created_at'],
            },
        ),
    ]
