# Generated by Django 4.2.28 on 2026-02-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_age_user_bio_user_grade_user_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, help_text='Firebase Authentication のユーザ UID', max_length=128, null=True, unique=True, verbose_name='Firebase UID'),
        ),
    ]
